

-- Table Schemas


DROP TABLE IF EXISTS transaction cascade;

DROP TABLE IF EXISTS recipient cascade;

DROP TABLE IF EXISTS transfer cascade;

DROP TABLE IF EXISTS account cascade;

DROP TABLE IF EXISTS bank cascade;

DROP TABLE IF EXISTS appointment cascade;

DROP TABLE IF EXISTS users cascade;

DROP TYPE IF EXISTS  transactionTypes;

DROP TYPE IF EXISTS  transferTypes;

CREATE TABLE users
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL,
    email     VARCHAR(25) UNIQUE NOT NULL,
    password  VARCHAR(25)        NOT NULL,
    phone     VARCHAR(15)

);
CREATE TYPE transactionTypes AS ENUM ('WITHDRAW', 'DEPOSIT');

CREATE TABLE transaction
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionType transactionTypes,
    amount FLOAT NOT NULL,
    transactionDate DATE ,
    transactionDescription VARCHAR(50) NOT NULL,
    user_id   INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TYPE transferTypes AS ENUM ('BETWEENACCOUNTS', 'TOSOMEONE');

CREATE TABLE recipient
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL,
    email     VARCHAR(25) UNIQUE NOT NULL,
    phone     VARCHAR(15),
    accountNumber  VARCHAR(25)        NOT NULL
);
CREATE TABLE transfer
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferType transferTypes,
    amount FLOAT NOT NULL,
    transferDate DATE ,
    transferDescription VARCHAR(50) NOT NULL,
    recipient_id   INT NOT NULL,
    user_id   INT NOT NULL,
    FOREIGN KEY (recipient_id) REFERENCES recipient (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);



CREATE TABLE bank
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25)        NOT NULL
);
CREATE TABLE account
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountNumber VARCHAR(25)        NOT NULL,
    amount FLOAT,
    bank_id   INT NOT NULL,
    FOREIGN KEY (bank_id) REFERENCES bank (id)
);
CREATE TABLE appointment
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE ,
    description VARCHAR (50) NOT NULL,
    location VARCHAR (20) NOT NULL,
    user_id   INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)

);
-- ////////////////////////////////////////////////////////////////////////////
--  Sample static test values
-- ////////////////////////////////////////////////////////////////////////////
-- If you want to keep your data, alternative 1
-- IF NOT EXISTS(SELECT * from airport where name='' and address='')
-- THEN
INSERT INTO users(firstname, lastname,email,password,phone)
VALUES ('Betul', 'Uyar','bet@gmail.com','12345','05550005555'),
       ('Fatma', 'Uyar','fatma@gmail.com','12345','05550005555'),
       ('Eslem', 'Uyar','eslemz@gmail.com','12345','05450004444');

INSERT INTO recipient(firstname, lastname,email,phone,accountNumber)
VALUES ('Betul', 'Uyar','bet@gmail.com','05550005555','1234567890'),
       ('Fatma', 'Uyar','fatma@gmail.com','05550005555','1234567899'),
       ('Eslem', 'Uyar','eslemz@gmail.com','05450004444','1234567888');


INSERT INTO transfer(transferType,amount, transferDate,transferDescription,recipient_id,user_id)
VALUES ('BETWEENACCOUNTS',100 ,'2021-11-13','Kira Bedeli','1','3'),
       ('TOSOMEONE',200, '2021-05-25','Harçlık','2','2'),
       ('BETWEENACCOUNTS',50, '2021-09-16','Borç 3','1','1');


-- If you want to keep your data, alternative 2
-- INSERT INTO airport (name, address)
-- SELECT 'SampleAirport',
--        'SampleAddress'
-- WHERE NOT EXISTS(
--         SELECT 1 FROM airport WHERE name = 'SampleAirport' AND address = 'SampleAddress'
--     );

-- If you want to keep your data, keep them on another data.sql file and rename this as schema.sql alternative 3


