

-- Table Schemas


DROP TABLE IF EXISTS transaction cascade;

DROP TABLE IF EXISTS recipient cascade;

DROP TABLE IF EXISTS transfer cascade;

DROP TABLE IF EXISTS account cascade;

DROP TABLE IF EXISTS bank cascade;

DROP TABLE IF EXISTS appointment cascade;

DROP TABLE IF EXISTS users cascade;

DROP TYPE IF EXISTS  transactionTypes;

DROP TYPE IF EXISTS  transferTypes;

CREATE TABLE bank
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25)        NOT NULL
);


CREATE TABLE account
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(250)        NOT NULL,
    balance FLOAT,
    bank_id   INT,
    FOREIGN KEY (bank_id) REFERENCES bank (id)
);

CREATE TABLE users
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL,
    username  VARCHAR(25),
    email     VARCHAR(25) UNIQUE NOT NULL,
    password  VARCHAR(25)        NOT NULL,
    phone     VARCHAR(15),
    account_id INT ,
    FOREIGN KEY (account_id) REFERENCES account(id)

);
CREATE TYPE transactionTypes AS ENUM ('WITHDRAW', 'DEPOSIT');

CREATE TABLE transaction
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionType transactionTypes,
    amount FLOAT NOT NULL,
    transaction_date DATE ,
    transaction_description VARCHAR(50) NOT NULL,
    is_success BOOLEAN ,
    user_id   INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TYPE transferTypes AS ENUM ('BETWEENACCOUNTS', 'TOSOMEONE');

CREATE TABLE recipient
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL,
    username  VARCHAR(25),
    email     VARCHAR(25) UNIQUE NOT NULL,
    phone     VARCHAR(15),
    account_id INT ,
    FOREIGN KEY (account_id) REFERENCES account(id)
);
CREATE TABLE transfer
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferType transferTypes,
    amount FLOAT NOT NULL,
    transfer_date DATE ,
    transfer_description VARCHAR(50) NOT NULL,
    is_success BOOLEAN ,
    recipient_id   INT NOT NULL,
    user_id   INT NOT NULL,
    FOREIGN KEY (recipient_id) REFERENCES recipient (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);


CREATE TABLE appointment
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date DATE ,
    description VARCHAR (50) NOT NULL,
    location VARCHAR (20) NOT NULL,
    user_id   INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)

);
-- ////////////////////////////////////////////////////////////////////////////
--  Sample static test values
-- ////////////////////////////////////////////////////////////////////////////
-- If you want to keep your data, alternative 1
-- IF NOT EXISTS(SELECT * from airport where name='' and address='')
-- THEN
INSERT INTO bank(name)
VALUES('Akbank'),
      ('Ziraat Bankası'),
      ('İş Bankası'),
      ('Vakıf Bankası'),
      ('Halk Bankası'),
      ('Garanti Bankası'),
      ('DenizBank'),
      ('Yapı Kredi Bankası'),
      ('Albaraka');


INSERT INTO account(account_number,balance,bank_id)
VALUES('1234567890',1500.00,1),
      ('1234567899',8765.00,3),
      ('1234567888',589.00,7),
      ('1234567889',2675.00,5),
      ('1234567887',4600.00,2);

INSERT INTO users(firstname, lastname,email,password,phone,account_id)
VALUES ('Betul', 'Uyar','betul@gmail.com','12345','05550005511',1),
       ('Fatma', 'Uyar','fatma@gmail.com','12345','05550005555',2),
       ('Eslem', 'Uyar','eslemz@gmail.com','22222','05450004444',3),
       ('Bedirhan', 'Ergün','bedirhan@gmail.com','11111','05550001111',4),
       ('Bilal', 'Olcay','bilal@gmail.com','12121','05450002222',5);

INSERT INTO recipient(firstname, lastname,email,phone,account_id)
VALUES ('Fatma', 'Uyar','fatma@gmail.com','05550005555',2),
       ('Eslem', 'Uyar','eslemz@gmail.com','05450004444',3),
       ('Bedirhan', 'Ergün','bedirhan@gmail.com','05550001111',4),
       ('Bilal', 'Olcay','bilal@gmail.com','05450002222',5),
       ('Betul', 'Uyar','bet@gmail.com','05550005511',1);


INSERT INTO transfer(transferType,amount, transfer_date,transfer_description,is_success, recipient_id,user_id)
VALUES ('BETWEENACCOUNTS',1000 ,'2021-11-13','Ocak Ayı Kira Bedeli',true,4,1),
       ('TOSOMEONE',200, '2021-05-25','Harçlık',true,5,1),
       ('BETWEENACCOUNTS',500, '2021-09-16','Ocak Ayı Burs Bedeli',true,3,2),
       ('BETWEENACCOUNTS',100 ,'2021-11-13','Borç Ödemesi',true,1,3),
       ('TOSOMEONE',200, '2021-05-25','Harçlık',true,4,2),
       ('BETWEENACCOUNTS',50, '2021-09-16','Borç 3',true,3,1);

INSERT INTO transaction(transactionType,amount, transaction_date,transaction_description,is_success,user_id)
VALUES ('WITHDRAW',500 ,'2021-11-13','500TL çekildi',true,1),
       ('DEPOSIT',250, '2021-05-25','250TL yatırıldı',true,2),
       ('DEPOSIT',200, '2021-05-25','200TL yatırıldı',true,4),
       ('WITHDRAW',170 ,'2021-11-13','170TL çekildi',true,3),
       ('DEPOSIT',260, '2021-05-25','260TL yatırıldı',true,5),
       ('WITHDRAW',50, '2021-09-16','50TL çekildi',true,1);




INSERT INTO appointment(appointment_date,description,location,user_id)
VALUES('2022-01-16','Hatalı işlem için talep edilen destek randevusu','online',2)

-- If you want to keep your data, alternative 2
-- INSERT INTO airport (name, address)
-- SELECT 'SampleAirport',
--        'SampleAddress'
-- WHERE NOT EXISTS(
--         SELECT 1 FROM airport WHERE name = 'SampleAirport' AND address = 'SampleAddress'
--     );

-- If you want to keep your data, keep them on another data.sql file and rename this as schema.sql alternative 3


